library(igraph)
library(qgraph)

#to rescale the positions so that there are no overlaps
rescale = function(x, a, b, c, d) {c + (x - a) / (b - a) * (d - c)}
#reading the edgelist that was generated by preProcessingForR.py
dat=read.csv("edgelist.csv",header=FALSE)
m = matrix(as.matrix(dat),ncol = ncol(dat),dimnames=NULL)
g = graph_from_edgelist(m, directed=FALSE)
l <- qgraph.layout.fruchtermanreingold(as_edgelist(g), area = 11 * (vcount(g) ^ 3), vcount = vcount(g),repulse.rad = (vcount(g) ^ 3.1))
l <- l * 2
binded <- cbind(l, rescale(degree(g), 0, max(degree(g)) / 3, 8, 18))
write.table(binded, file="positions.csv", sep = ",", col.names = F)
#Modified Fruchterman Reingold to our needs and written into the file positions.csv
print("Positions of nodes obtained!")
