#in the format:
"""
{
    "node": [
        {
            "id": "0",
            "position": {
             "x": "477.03848",
             "y": "-25.933804"
            }
            "size": {
             "value": "19.714287"
            }
        }
    ]
    "links": [
       {
          "id": "8489",
          "source": "0",
          "target": "29",
          "attvalues": {
             "attvalue": [
                {
                   "for": "ts_start",
                   "value": "2020-07-22 10:27:54"
                },
                {
                   "for": "ts_end",
                   "value": "2020-07-22 10:30:57"
                }
             ]
          }
        }
    ]
}"""
import csv
import json
import numpy as np
import pandas as pd

csvfileNode = open('positions.csv', 'r') #opening the positions file generated by the R file
jsonfile1 = open('Viz/data/mean_of_graph_durations.json', 'w') #opening a json to write into
csvfileLink = open('mean_of_graph_durations.csv', 'r') #opening the file for the links

jsonfile1.write("{\"node\":[")
first = True
for row in csv.reader(csvfileNode, delimiter=','):
    if first:
        first = False
    else:
        jsonfile1.write(",") 
    d = {"id" : row[0], "position" : {"x": row[1], "y": row[2]}, "size" : {"value": row[4]}, "color": {"value": row[3]}}
    json.dump(d, jsonfile1)
 
jsonfile1.write("],\"links\":[")
first, i = True, 0
for row in csv.reader(csvfileLink, delimiter=','):
    i += 1
    if first:
        first = False
    else:
        jsonfile1.write(",") 
    d = {"id": i, "source": row[0], "target": row[1], "weight": row[2],
        "attvalues": 
            { "attvalue": [{
                "for": "ts_start",
                "value": row[3]
                },
                {
                "for": "ts_end",
                "value": row[4]
                }
            ]} 
        }
    json.dump(d, jsonfile1)
jsonfile1.write("]}")
print("JSON ready!")
